image: archlinux
sources:
  - "https://github.com/49e94b8f256530dc0d41f740dfe8a4c1/snake.git"
secrets:
  - b03d783e-d793-479d-8558-082abb0ab74a
packages:
  - npm
  - nodejs-lts-fermium
tasks:
  - setup: |
      node -v
      npm -v
  - install: |
      cd snake
      npm ci
  - test: |
      cd snake
      npm test
  - build: |
      cd snake
      npm run build
  - deploy: |
      cd snake
      DEPLOY_HOST=168.119.234.216
      DEPLOY_USER=ken
      scp -o StrictHostKeyChecking=no -rv dist/* $DEPLOY_USER@$DEPLOY_HOST:/var/www/html/snake
